package PlayGame;

import java.awt.event.ActionEvent;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import word_game.Randomize;
import word_game.Trie;
import wordnet_jaws.WordnetGUI;

/**
 *
 * @author arnob
 */
public class PlayAnagram extends javax.swing.JFrame {
   
    String wordchar;
    Set set=new TreeSet();
    Set setc=new TreeSet();
    Set seti=new TreeSet();
    Trie t;

    
    public PlayAnagram(Trie t) {
        this.t=t;
        initComponents();
        word.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        level1 = new javax.swing.JButton();
        level2 = new javax.swing.JButton();
        level3 = new javax.swing.JButton();
        letter1 = new javax.swing.JButton();
        letter2 = new javax.swing.JButton();
        letter5 = new javax.swing.JButton();
        letter3 = new javax.swing.JButton();
        letter4 = new javax.swing.JButton();
        letter6 = new javax.swing.JButton();
        letter8 = new javax.swing.JButton();
        letter7 = new javax.swing.JButton();
        incorrect = new java.awt.TextArea();
        correct = new java.awt.TextArea();
        word = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        rules = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        anagram = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();
        GetNet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Anagram");

        level1.setText("LEVEL 1");
        level1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level1ActionPerformed(evt);
            }
        });

        level2.setText("LEVEL 2");
        level2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level2ActionPerformed(evt);
            }
        });

        level3.setText("LEVEL 3");
        level3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level3ActionPerformed(evt);
            }
        });

        letter1.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        letter1.setText(" ");
        letter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letter1ActionPerformed(evt);
            }
        });

        letter2.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        letter2.setText(" ");
        letter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letter2ActionPerformed(evt);
            }
        });

        letter5.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        letter5.setText(" ");
        letter5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letter5ActionPerformed(evt);
            }
        });

        letter3.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        letter3.setText(" ");
        letter3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letter3ActionPerformed(evt);
            }
        });

        letter4.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        letter4.setText(" ");
        letter4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letter4ActionPerformed(evt);
            }
        });

        letter6.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        letter6.setText(" ");
        letter6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letter6ActionPerformed(evt);
            }
        });

        letter8.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        letter8.setText(" ");
        letter8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letter8ActionPerformed(evt);
            }
        });

        letter7.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        letter7.setText(" ");
        letter7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letter7ActionPerformed(evt);
            }
        });

        incorrect.setBackground(new java.awt.Color(255, 255, 255));
        incorrect.setEditable(false);
        incorrect.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        incorrect.setForeground(new java.awt.Color(204, 0, 0));

        correct.setBackground(new java.awt.Color(255, 255, 255));
        correct.setEditable(false);
        correct.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        correct.setForeground(new java.awt.Color(0, 102, 0));

        word.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordActionPerformed(evt);
            }
        });

        submit.setText("SUBMIT");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        rules.setText("How to");
        rules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesActionPerformed(evt);
            }
        });

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel1.setText("INCORRECT");

        jLabel2.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel2.setText("CORRECT");

        anagram.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        anagram.setText("ANAGRAM");
        anagram.setToolTipText("");
        anagram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anagramMouseClicked(evt);
            }
        });

        GetNet.setText("GetNet");
        GetNet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetNetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GetNet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rules)
                        .addGap(18, 18, 18)
                        .addComponent(back))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(letter1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(letter2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(letter3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(letter4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(letter5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(letter6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(letter7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(letter8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(correct, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(incorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(level1)
                        .addGap(18, 18, 18)
                        .addComponent(level2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anagram)
                            .addComponent(level3)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(progress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(154, 154, 154)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(word, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(submit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clear)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(anagram)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(level2)
                    .addComponent(level1)
                    .addComponent(level3))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letter1)
                    .addComponent(letter2)
                    .addComponent(letter3)
                    .addComponent(letter4)
                    .addComponent(letter6)
                    .addComponent(letter7)
                    .addComponent(letter8)
                    .addComponent(letter5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(word, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submit)
                    .addComponent(clear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(incorrect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(rules)
                    .addComponent(GetNet))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void level1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level1ActionPerformed
        if(evt.getSource()==level1){
            letter6.setVisible(false);
            level2ActionPerformed(evt);
        }
    }//GEN-LAST:event_level1ActionPerformed

    private void level2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level2ActionPerformed
        if(evt.getSource()==level1){
            letter7.setVisible(false);
            letter8.setVisible(false);
            playAgain(evt);
        }
        
        else if(evt.getSource()==level2){
            letter6.setVisible(true);
            letter7.setVisible(false);
            letter8.setVisible(false);
            playAgain(evt);
        }
    }//GEN-LAST:event_level2ActionPerformed

    private void level3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level3ActionPerformed
        if(evt.getSource()==level3){
            letter6.setVisible(true);
            letter7.setVisible(true);            
            letter8.setVisible(true);
            playAgain(evt);
        }
    }//GEN-LAST:event_level3ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        word.setText(null);
    }//GEN-LAST:event_clearActionPerformed

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
       submit();
    }//GEN-LAST:event_submitMouseClicked

    private void letter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letter1ActionPerformed
        // TODO add your handling code here:
        String s=letter1.getText();
        String s2=word.getText();
        s2+=s;
        word.setText(s2); 
    }//GEN-LAST:event_letter1ActionPerformed

    private void letter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letter2ActionPerformed
        // TODO add your handling code here:
        String s=letter2.getText();
        String s2=word.getText();
        s2+=s;
        word.setText(s2); 
    }//GEN-LAST:event_letter2ActionPerformed

    private void letter3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letter3ActionPerformed
        // TODO add your handling code here:
        String s=letter3.getText();
        String s2=word.getText();
        s2+=s;
        word.setText(s2); 
    }//GEN-LAST:event_letter3ActionPerformed

    private void letter4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letter4ActionPerformed
        String s=letter4.getText();
        String s2=word.getText();
        s2+=s;
        word.setText(s2); 
    }//GEN-LAST:event_letter4ActionPerformed

    private void letter5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letter5ActionPerformed
        // TODO add your handling code here:
        String s=letter5.getText();
        String s2=word.getText();
        s2+=s;
        word.setText(s2); 
    }//GEN-LAST:event_letter5ActionPerformed

    private void letter6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letter6ActionPerformed
        // TODO add your handling code here:
        String s=letter6.getText();
        String s2=word.getText();
        s2+=s;
        word.setText(s2); 
    }//GEN-LAST:event_letter6ActionPerformed

    private void letter7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letter7ActionPerformed
        // TODO add your handling code here:
        String s=letter7.getText();
        String s2=word.getText();
        s2+=s;
        word.setText(s2); 
    }//GEN-LAST:event_letter7ActionPerformed

    private void letter8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letter8ActionPerformed
        // TODO add your handling code here:
        String s=letter8.getText();
        String s2=word.getText();
        s2+=s;
        word.setText(s2); 
    }//GEN-LAST:event_letter8ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        submit();
    }//GEN-LAST:event_submitActionPerformed

    private void wordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordActionPerformed
        // TODO add your handling code here:
        submit();
    }//GEN-LAST:event_wordActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==back){
            this.dispose();
            PlayMenu pm=new PlayMenu(t);
            pm.setVisible(true);
            pm.setResizable(false);
        }
    }//GEN-LAST:event_backActionPerformed

    private void anagramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anagramMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, set, "Prefixer Solutions", INFORMATION_MESSAGE);
    }//GEN-LAST:event_anagramMouseClicked

    private void rulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "1. solver needs to make as many words as possible using all the letters once.\n" +
"2. there are 3 levels:\n" +
"	level 1: 5 letters.\n" +
"	level 2: 6 letters.\n" +
"	level 3: 8 letters.\n" +
"3. use only a-z.\n" +
"4. enter the words in the provided text field either by typing 'em or by clicking on the letters and then press enter or click submit.\n" +
"5. click back to go to the play menu.\n" +
"6. click clear to clear the text field.\n" +
"7. click level buttons to restart the game.");
    }//GEN-LAST:event_rulesActionPerformed

    private void GetNetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetNetActionPerformed
        if(evt.getSource()==GetNet){
            WordnetGUI wn = new WordnetGUI();
            wn.setVisible(true);
            wn.setResizable(false);
        }        
    }//GEN-LAST:event_GetNetActionPerformed

    private void submit(){
        if(set.contains(word.getText().trim())){
            String s=correct.getText();
            if(!setc.contains(word.getText().trim())){
                setc.add(word.getText().trim());
                s+="\n "+word.getText().trim();
                correct.setText(s);
            }
            
            word.setText("");
        }
        
        else{
            String s=incorrect.getText();
            if(!seti.contains(word.getText().trim())){
                seti.add(word.getText().trim());
                s+="\n "+word.getText().trim();
                incorrect.setText(s); 
            }
             
            word.setText("");
        }
        
        int value=(int) (((double)setc.size()/(double)set.size())*100.0);
        progress.setStringPainted(true);
        progress.setValue(value);
        progress.setString(value + "%   ["+setc.size()+" Of "+set.size()+"]");
    }
    
    private void playAgain(ActionEvent e) {
        word.setEditable(true);
        if(e.getSource()==level1){
            Randomize r=new Randomize(t);
            r.number(2);
            wordchar=r.validWordAna();
            set=r.getSet();
            word.setText(null);
            correct.setText(null);
            incorrect.setText(null);
            initLettersL1();
        }
        else if(e.getSource()==level2){
            Randomize r=new Randomize(t);
            r.number(3);
            wordchar=r.validWordAna();
            set=r.getSet();
            word.setText(null);
            correct.setText(null);
            incorrect.setText(null);
            initLettersL2();
        }
        
        else if(e.getSource()==level3){
            Randomize r=new Randomize(t);
            r.number(4);
            wordchar=r.validWordAnal3();
            set=r.getSet();
            word.setText(null);
            correct.setText(null);
            incorrect.setText(null);
            initLettersL3();
        }
        
        setc=new TreeSet();
        seti=new TreeSet();
        progress.setStringPainted(true);
        progress.setValue((int)((setc.size()/set.size())*100.0));
        progress.setString("0%   ["+setc.size()+" Of "+set.size()+"]");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GetNet;
    private javax.swing.JLabel anagram;
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private java.awt.TextArea correct;
    private java.awt.TextArea incorrect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton letter1;
    private javax.swing.JButton letter2;
    private javax.swing.JButton letter3;
    private javax.swing.JButton letter4;
    private javax.swing.JButton letter5;
    private javax.swing.JButton letter6;
    private javax.swing.JButton letter7;
    private javax.swing.JButton letter8;
    private javax.swing.JButton level1;
    private javax.swing.JButton level2;
    private javax.swing.JButton level3;
    private javax.swing.JProgressBar progress;
    private javax.swing.JButton rules;
    private javax.swing.JButton submit;
    private javax.swing.JTextField word;
    // End of variables declaration//GEN-END:variables

    private void initLettersL1() {
        letter1.setText(""+wordchar.charAt(0)+"");
        letter2.setText(""+wordchar.charAt(1)+"");
        letter3.setText(""+wordchar.charAt(2)+"");
        letter4.setText(""+wordchar.charAt(3)+"");
        letter5.setText(""+wordchar.charAt(4)+"");
    }
    
    private void initLettersL2() {
        initLettersL1();
        letter6.setText(""+wordchar.charAt(5)+"");
    }
    
    private void initLettersL3(){
        initLettersL2();
        letter7.setText(""+wordchar.charAt(6)+"");
        letter8.setText(""+wordchar.charAt(7)+"");
        
    }
    
}
